apiVersion: v1
kind: Service
metadata:
  labels:
    io.mad.service: keycloak-service
  name: keycloak-service
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.mad.service: keycloak-service
status:
  loadBalancer: {}
