apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.mad.service: keycloak-service
  name: keycloak-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.mad.service: keycloak-service
  strategy: {}
  template:
    metadata:
      labels:
        io.mad.network/mad-network: "true"
        io.mad.service: keycloak-service
    spec:
      containers:
        - args:
            - start-dev
          env:
            - name: KC_DB
              valueFrom:
                configMapKeyRef:
                  key: KC_DB
                  name: env-keycloak
            - name: KC_DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: KC_DB_PASSWORD
                  name: env-keycloak
            - name: KC_DB_SCHEMA
              valueFrom:
                configMapKeyRef:
                  key: KC_DB_SCHEMA
                  name: env-keycloak
            - name: KC_DB_URL_HOST
              valueFrom:
                configMapKeyRef:
                  key: KC_DB_URL_HOST
                  name: env-keycloak
            - name: KC_DB_URL_PORT
              valueFrom:
                configMapKeyRef:
                  key: KC_DB_URL_PORT
                  name: env-keycloak
            - name: KC_DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: KC_DB_USERNAME
                  name: env-keycloak
            - name: KEYCLOAK_ADMIN
              valueFrom:
                configMapKeyRef:
                  key: KEYCLOAK_ADMIN
                  name: env-keycloak
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: KEYCLOAK_ADMIN_PASSWORD
                  name: env-keycloak
            - name: KEYCLOAK_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  key: KEYCLOAK_HOSTNAME
                  name: env-keycloak
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_DB
                  name: env-keycloak
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PASSWORD
                  name: env-keycloak
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_USER
                  name: env-keycloak
            - name: PROXY_ADDRESS_FORWARDING
              valueFrom:
                configMapKeyRef:
                  key: PROXY_ADDRESS_FORWARDING
                  name: env-keycloak
          image: ghcr.io/mad-goat-project/keycloak:main
          name: mad-keycloak-service
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 500m
              memory: "500Mi"
            requests:
              cpu: 250m
              memory: "250Mi"
      restartPolicy: Always
status: {}
