apiVersion: v1
kind: Service
metadata:
  annotations:
    traefik.enable: "true"
    traefik.http.routers.keycloak-service.entrypoints: web
    traefik.http.routers.keycloak-service.rule: Host(`keycloak.mad.localhost`) && PathPrefix(`/`) && (Method(`GET`) || Method(`POST`))
    traefik.http.services.keycloak-service.loadbalancer.server.port: "8080"
  creationTimestamp: null
  labels:
    io.mad.service: keycloak-service
  name: keycloak-service
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.mad.service: keycloak-service
status:
  loadBalancer: {}
