apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  creationTimestamp: null
  labels:
    io.mad.service: {{ .Values.rabbitmq.service.name }}
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      io.mad.service: {{ .Values.rabbitmq.service.name }}
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
      creationTimestamp: null
      labels:
        io.mad.network/mad-network: "true"
        io.mad.service: {{ .Values.rabbitmq.service.name }}
    spec:
      containers:
        - image: {{ .Values.rabbitmq.image.repository }}:{{ .Values.rabbitmq.image.tag }}
          name: rabbitmq
          ports:
            - containerPort: {{ .Values.rabbitmq.port1 }}
            - containerPort: {{ .Values.rabbitmq.port2 }}
          resources: {}
          volumeMounts:
      restartPolicy: Always
      volumes: []
status: {}
