version: "3"

services:
  ####################### MAD GOAT SERVICES ###########################

  #####################################################################
  # Keycloak
  db-keycloak-service:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - mad-network

  keycloak-service:
    command: start-dev
    build: ./keycloak
    env_file:
      - .env
    ports:
      - 8080:8080
    depends_on:
      - db-keycloak-service
    networks:
      - mad-network

  #####################################################################
  # Traefik
  traefik-reverse-proxy:
    image: traefik:latest
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8082:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  #####################################################################
  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - mad-network
  #####################################################################
  # Web App
  webapp:
    image: ghcr.io/mad-goat-project/mad-web-app:main
    env_file:
      - .env
    ports:
      - 3000:3000
    networks:
      - mad-network
  #####################################################################
  # Lesson Service
  lesson-service:
    image: ghcr.io/mad-goat-project/mad-lessons-service:main
    ports:
      - "3001:3000"
    env_file:
      - .env
    depends_on:
      - db-lesson-service
    networks:
      - mad-network

  db-lesson-service:
    image: postgres:14.1-alpine
    restart: always
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - ./db-lesson-service:/var/lib/postgresql/data

networks:
  mad-network:
    name: mad-network

#####################################################################
# Configurations
volumes:
  postgres_data:
    driver: local
