version: "3"

services:
  ####################### MAD GOAT SERVICES ###########################

  #####################################################################
  # Keycloak
  db-keycloak-service:
    image: postgres:15.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./envs/.env.keycloak
    ports:
      - 5432:5432
    networks:
      - mad-network

  keycloak-service:
    container_name: keycloak
    command: start-dev
    build: ./keycloak
    env_file:
      - ./envs/.env.keycloak
    ports:
      - 8080:8080
    depends_on:
      - db-keycloak-service
    networks:
      - mad-network

  #####################################################################
  # Traefik
  traefik-reverse-proxy:
    image: traefik:2.10.1
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8082:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  #####################################################################
  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - mad-network
  #####################################################################
  # Web App
  webapp:
    image: ghcr.io/mad-goat-project/mad-web-app:main
    env_file:
      - ./envs/.env.webapp
    ports:
      - 3000:80
    networks:
      - mad-network
  #####################################################################
  # Lesson Service
  lesson-service:
    image: ghcr.io/mad-goat-project/mad-lessons-service:main
    ports:
      - "3001:3000"
    env_file:
      - ./envs/.env.lesson
      - ./envs/.env.keycloak.secrets
    depends_on:
      - db-lesson-service
    labels:
      # Explicitly instruct Traefik to expose this service
      - "traefik.enable=true"
      # Router configuration
      ## Rule based on the Host of the request
      - "traefik.http.routers.lesson-service.rule=Host(`lesson-service.local`)"
      ## Use PathPrefixStrip to remove the path prefix from the request before forwarding
      - "traefik.http.routers.lesson-service.middlewares=lesson-service-stripprefix"
      # Service configuration
      ## Set the service name
      - "traefik.http.services.lesson-service-service.loadbalancer.server.port=3000"
      # Middleware configuration
      ## Define the PathPrefixStrip middleware
      - "traefik.http.middlewares.lesson-service-stripprefix.stripprefix.prefixes=/lesson-service"
    networks:
      - mad-network

  db-lesson-service:
    image: postgres:14.1-alpine
    restart: always
    env_file:
      - ./envs/.env.lesson
    ports:
      - "5433:5432"
    volumes:
      - ./data/db-lesson-service:/var/lib/postgresql/data
    networks:
      - mad-network

  #####################################################################
  # Category: Open Source Software
  # Lesson: Inconsistent Security Standards

  #Safe Service
  mad4shell-service-safe:
    image: ghcr.io/mad-goat-project/mad-goat4shell-service:safe
    ports:
      - "3002:8080"
    networks:
      - mad-network

  #Unsafe Service
  mad4shell-service-unsafe:
    image: ghcr.io/mad-goat-project/mad-goat4shell-service:unsafe
    ports:
      - "3003:8080"
    networks:
      - mad-network

  #####################################################################
  # Category: Open Source Software
  # Lesson: Unknown Source Code Origins

  scoreboard-service:
    image: ghcr.io/mad-goat-project/mad-scoreboard-service:main
    restart: always
    env_file:
      - ./envs/.env.scoreboard
      - ./envs/.env.keycloak.secrets
    ports:
      - "3004:3000"
    depends_on:
      - db-scoreboard-service
    networks:
      - mad-network

  db-scoreboard-service:
    container_name: db-scoreboard-service
    image: mongo:6.0
    ports:
      - 27017:27017
    volumes:
      - ./data/db-scoreboard-service:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    networks:
      - mad-network

  ##  #####################################################################
  ##  ## Jekyll Documentation Service

  jekyll-service:
    image: ghcr.io/mad-goat-project/mad-goat-docs:main
    restart: always
    ports:
      - "4000:80"
    networks:
      - mad-network

# Configurations
volumes:
  postgres_data:
    driver: local
  prometheus_data: {}
  grafana_data: {}
  minio_storage: {}

networks:
  mad-network:
    name: mad-network
