apiVersion: v1
kind: Service
metadata:
  annotations:
    traefik.enable: "true"
    traefik.http.routers.rabbitmq-service.entrypoints: web
    traefik.http.routers.rabbitmq-service.rule: Host(`rabbitmq.mad.localhost`)
    traefik.http.services.rabbitmq-service.loadbalancer.server.port: "15672"
  creationTimestamp: null
  labels:
    io.mad.service: rabbitmq
  name: rabbitmq
spec:
  ports:
    - name: "5672"
      port: 5672
      targetPort: 5672
    - name: "15672"
      port: 15672
      targetPort: 15672
  selector:
    io.mad.service: rabbitmq
status:
  loadBalancer: {}
