apiVersion: v1
kind: Service
metadata:
  annotations:
    traefik.enable: "true"
    traefik.http.routers.traefik-service.entrypoints: web
    traefik.http.routers.traefik-service.rule: Host(`traefik.mad.localhost`)
    traefik.http.services.traefik-service.loadbalancer.server.port: "8080"
  creationTimestamp: null
  labels:
    io.mad.service: traefik-reverse-proxy
  name: traefik-reverse-proxy
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
    - name: "8082"
      port: 8082
      targetPort: 8080
  selector:
    io.mad.service: traefik-reverse-proxy
status:
  loadBalancer: {}
