version: "3"

volumes:
  postgres_data:
    driver: local
  prometheus_data: {}
  grafana_data: {}
  minio_storage: {}

networks:
  mad-network:
    name: mad-network
    internal: true
  keycloak-network:
    name: keycloak-network
    internal: true
  traefik-network:
    name: traefik-network
    external: true
