version: "3"
services:
  #####################################################################
  # Web App
  webapp:
    #image: ghcr.io/mad-goat-project/mad-web-app:main
    container_name: mad-web-app
    build:
      context: /Users/luisventuzelos/Documents/GitHub/MAD/mad-web-app
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
    env_file:
      - ./envs/.env.webapp
    ports:
      - 3000:80
    #####################################################################
    # Lesson Service
  lesson-service:
    image: ghcr.io/mad-goat-project/mad-lessons-service:main
    container_name: mad-lesson-service
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
    ports:
      - "3001:3000"
    env_file:
      - ./envs/.env.lesson
      - ./envs/.env.keycloak.secrets
    depends_on:
      - db-lesson-service
    networks:
      - mad-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lesson-service.rule=Host(`localhost`) && PathPrefix(`/lessons`)"
      - "traefik.http.middlewares.strip-prefix.stripprefix.prefixes=/lessons"
      - "traefik.http.routers.lesson-service.middlewares=strip-prefix@docker"
      - "traefik.http.routers.lesson-service.entrypoints=web"
      - "traefik.http.services.lesson-service.loadbalancer.server.port=3000"

  db-lesson-service:
    image: postgres:14.1-alpine
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
    restart: always
    env_file:
      - ./envs/.env.lesson
    ports:
      - "5433:5432"
    volumes:
      - ./data/db-lesson-service:/var/lib/postgresql/data
    networks:
      - mad-network

  #####################################################################
  # Category: Open Source Software
  # Lesson: Inconsistent Security Standards

  #Safe Service
  mad4shell-service-safe:
    image: ghcr.io/mad-goat-project/mad-goat4shell-service:safe
    container_name: mad4shell-service-safe
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
    ports:
      - "3002:8080"
    networks:
      - mad-network

  #Unsafe Service
  mad4shell-service-unsafe:
    image: ghcr.io/mad-goat-project/mad-goat4shell-service:unsafe
    container_name: mad4shell-service-unsafe
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
    ports:
      - "3003:8080"
    networks:
      - mad-network

  #####################################################################
  # Category: Open Source Software
  # Lesson: Unknown Source Code Origins

  scoreboard-service:
    image: ghcr.io/mad-goat-project/mad-scoreboard-service:main
    container_name: mad-scoreboard-service
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
    restart: always
    env_file:
      - ./envs/.env.scoreboard
      - ./envs/.env.keycloak.secrets
    ports:
      - "3004:3000"
    depends_on:
      - db-scoreboard-service
    networks:
      - mad-network

  db-scoreboard-service:
    container_name: db-scoreboard-service
    image: mongo:6.0
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
    ports:
      - 27017:27017
    volumes:
      - ./data/db-scoreboard-service:/data/db
    env_file:
      - ./envs/.env.scoreboard
    networks:
      - mad-network
